import "./styles/globals.css";
import Navbar from "./components/Navbar";
import { UserProvider } from "./context/UserContext";
import ClientLayout from "./ClientProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <ClientLayout>{children}</ClientLayout>
        </UserProvider>
      </body>
    </html>
  );
}
